blog/urls.py
from . import views
from django.urls import path

urlpatterns = [
    path('contact/', views.contact_us, name='contact_us'),
    path("<slug:slug>/", views.PostDetail.as_view(), name="post_detail"),
    path("like/<slug:slug>", views.PostLike.as_view(), name="post_like"),
    path("", views.PostList.as_view(), name="home"),
]

fishing_journal/urls.py
from django.urls import path
from . import views

app_name = 'fishing_journal'

urlpatterns = [
    path('create/', views.create_entry, name='create_entry'),
    path('update/<int:entry_id>/', views.update_entry, name='update_entry'),
    path('delete/<int:entry_id>/', views.delete_entry, name='delete_entry'),
    path('entry_base/', views.entry_base, name='entry_base'),
]

fishingblog/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('summernote/', include('django_summernote.urls')),
    path("accounts/", include("allauth.urls")),
    path("", include("blog.urls")),
    path("fishing_journal/", include("fishing_journal.urls")),
]

blog/models.py
from django.db import models
from django.contrib.auth.models import User
from cloudinary.models import CloudinaryField

# Create your models here.

STATUS = ((0, "Draft"), (1, "Published"))


class Post(models.Model):
    title = models.CharField(max_length=200, unique=True)
    slug = models.SlugField(max_length=200, unique=True)
    author = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name="blog_posts"
    )
    featured_image = CloudinaryField('image', default='placeholder')
    excerpt = models.TextField(blank=True)
    updated_on = models.DateTimeField(auto_now=True)
    content = models.TextField()
    created_on = models.DateTimeField(auto_now_add=True)
    status = models.IntegerField(choices=STATUS, default=0)
    likes = models.ManyToManyField(
        User, related_name='blogpost_like', blank=True)

    class Meta:
        ordering = ["-created_on"]

    def __str__(self):
        return self.title

    def number_of_likes(self):
        return self.likes.count()


class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE,
                             related_name="comments")
    name = models.CharField(max_length=80)
    email = models.EmailField()
    body = models.TextField()
    created_on = models.DateTimeField(auto_now_add=True)
    approved = models.BooleanField(default=False)

    class Meta:
        ordering = ["created_on"]

    def __str__(self):
        return f"Comment {self.body} by {self.name}"


class ContactMessage(models.Model):
    name = models.CharField(max_length=100)
    email = models.EmailField()
    subject = models.CharField(max_length=200)
    message = models.TextField()
    created_on = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.subject

fishing_journal/models.py
from django.db import models
from django.contrib.auth.models import User


class FishingJournalEntry(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    title = models.CharField(max_length=100)
    location = models.CharField(max_length=100)
    date = models.DateField()
    catch_details = models.TextField()
    notes = models.TextField(blank=True)

    class Meta:
        app_label = 'fishing_journal'

blog/forms.py
from .models import Comment, ContactMessage
from django import forms


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('body',)


class ContactForm(forms.ModelForm):
    class Meta:
        model = ContactMessage
        fields = ['name', 'email', 'subject', 'message']

fishing_journal/forms.py
from django import forms
from .models import FishingJournalEntry


class FishingJournalEntryForm(forms.ModelForm):
    class Meta:
        model = FishingJournalEntry
        fields = ['title', 'location', 'date', 'catch_details', 'notes']
        widgets = {
            'date': forms.DateInput(attrs={'type': 'date'})
        }

blog/views.py
from django.shortcuts import render, get_object_or_404, reverse, redirect
from django.views import generic, View
from django.http import HttpResponseRedirect
from .models import Post
from .forms import CommentForm, ContactForm
from django.contrib import messages


class PostList(generic.ListView):
    model = Post
    queryset = Post.objects.filter(status=1).order_by("-created_on")
    template_name = "index.html"
    paginate_by = 3


class PostDetail(View):

    def get(self, request, slug, *args, **kwargs):
        queryset = Post.objects.filter(status=1)
        post = get_object_or_404(queryset, slug=slug)
        comments = post.comments.filter(approved=True).order_by("-created_on")
        liked = False
        if post.likes.filter(id=self.request.user.id).exists():
            liked = True

        return render(
            request,
            "post_detail.html",
            {
                "post": post,
                "comments": comments,
                "commented": False,
                "liked": liked,
                "comment_form": CommentForm()
            },
        )

    def post(self, request, slug, *args, **kwargs):
        queryset = Post.objects.filter(status=1)
        post = get_object_or_404(queryset, slug=slug)
        comments = post.comments.filter(approved=True).order_by("-created_on")
        liked = False
        if post.likes.filter(id=self.request.user.id).exists():
            liked = True

        comment_form = CommentForm(data=request.POST)

        if comment_form.is_valid():
            comment_form.instance.email = request.user.email
            comment_form.instance.name = request.user.username
            comment = comment_form.save(commit=False)
            comment.post = post
            comment.save()
        else:
            comment_form = CommentForm

        return render(
            request,
            "post_detail.html",
            {
                "post": post,
                "comments": comments,
                "commented": True,
                "liked": liked,
                "comment_form": CommentForm()
            },
        )


class PostLike(View):

    def post(self, request, slug):
        post = get_object_or_404(Post, slug=slug)

        if post.likes.filter(id=request.user.id).exists():
            post.likes.remove(request.user)
        else:
            post.likes.add(request.user)
        return HttpResponseRedirect(reverse('post_detail', args=[slug]))


def contact_us(request):
    if request.method == 'POST':
        form = ContactForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Contact message sent')
            return redirect(reverse('home'))
    else:
        form = ContactForm()

    return render(request, 'contact_us.html', {'form': form})

fishing_journal/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import FishingJournalEntry
from .forms import FishingJournalEntryForm
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.views.generic import ListView


@login_required
def entry_base(request):
    return ListView.as_view(
        model=FishingJournalEntry,
        paginate_by=4,
        template_name='fishing_journal/entry_base.html',
        context_object_name='entries',
        queryset=FishingJournalEntry.objects.filter(user=request.user),
    )(request)


@login_required
def create_entry(request):
    if request.method == 'POST':
        form = FishingJournalEntryForm(request.POST)
        if form.is_valid():
            entry = form.save(commit=False)
            entry.user = request.user
            entry.save()
            messages.success(request, 'Entry Saved')
            return redirect('fishing_journal:entry_base')
    else:
        form = FishingJournalEntryForm()
    return render(request, 'fishing_journal/create_entry.html', {'form': form})


@login_required
def update_entry(request, entry_id):
    entry = get_object_or_404(FishingJournalEntry, id=entry_id, user=request.user)

    if request.method == 'POST':
        form = FishingJournalEntryForm(request.POST, instance=entry)
        if form.is_valid():
            form.save()
            messages.success(request, 'Entry Updated')
            return redirect('fishing_journal:entry_base')

    form = FishingJournalEntryForm(instance=entry)
    return render(request, 'fishing_journal/update_entry.html', {'form': form})


@login_required
def delete_entry(request, entry_id):
    entry = get_object_or_404(FishingJournalEntry, id=entry_id, user=request.user)

    if request.method == 'POST':
        entry.delete()
        messages.success(request, 'Entry Deleted')
        return redirect('fishing_journal:entry_base')

    return render(request, 'fishing_journal/delete_entry.html', {'entry': entry})

templates/base.html
{% load static %}

<!DOCTYPE html>
<html class="h-100" lang="en">

<head>
    <title>Swedish Angler's Diary</title>
    <meta charset="UTF-8">
    <meta name="author" content="Pierre Slagbrand">
    <meta name="publisher" content="Pierre Slagbrand">
    <meta name="keywords" content="website, blog, journal, fishing, sweden">
    <meta name="description" content="website, blog, journal, fishing, sweden">
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link rel="icon" type="image/png" href="{% static 'images/fishfavicon32.png' %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-gtEjrD/SeCtmISkJkNUaaKMoLD0//ElJ19smozuHV6z3Iehds+3Ulb9Bn9Plx0x4" crossorigin="anonymous">
    </script>
    <script src="https://kit.fontawesome.com/868176c90e.js" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>

<body class="d-flex flex-column h-100 main-bg">

    <!-- Navigation -->
    <nav class="navbar navbar-expand-lg navbar-light">
        <div class="container-fluid">
            <a class="navbar-brand" href="{% url 'home' %}"><span class="brand">Swedish Angler's Diary</span></a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarText"
                    aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarText">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                    <li class="nav-item">
                        <a class="nav-link" id="navlinkhome" aria-current="page" href="{% url 'home' %}">Home</a>
                    </li>
                    {% if user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'fishing_journal:entry_base' %}">Fishing Journal</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'account_logout' %}">Logout</a>
                    </li>
                    {% else %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'account_signup' %}">Register</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'account_login' %}">Login</a>
                    </li>
                    {% endif %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'contact_us' %}">Contact</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>

    <!-- Messages Container -->
    <div class="container text-center" id="messages-container">
        <div class="row">
            <div class="col-md-8 offset-md-2">
                {% for message in messages %}
                <div class="alert {{ message.tags }} alert-dismissible fade show msg" role="alert">
                    {{ message | safe }}
                    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                </div>
                {% endfor %}
            </div>
        </div>
    </div>

    <!-- Pagination -->
    {% if is_paginated %}
    <nav aria-label="Page navigation">
        <ul class="pagination justify-content-center">
            {% if page_obj.has_previous %}
            <li><a href="?page={{ page_obj.previous_page_number }}" class="page-link">&laquo; PREV </a></li>
            {% endif %}
            {% if page_obj.has_next %}
            <li><a href="?page={{ page_obj.next_page_number }}" class="page-link"> NEXT &raquo;</a></li>
            {% endif %}
        </ul>
    </nav>
    {% endif %}

    <!-- Main content -->
    <main class="flex-shrink-0 main-bg">
        {% block content %}
        <!-- Content Goes here -->
        {% endblock content %}
    </main>

    <!-- Footer -->
    <footer class="footer mt-auto py-3 dark-bg">
        <p class="m-0 text-center text-white">Made by Code Institute Student</p>
        <p class="m-0 text-center text-white">Follow us:
            <a href="https://www.facebook.com" target="_blank" aria-label="Facebook">
                <i class="fab fa-facebook ms-3"></i>
            </a>
            <a href="https://twitter.com" target="_blank" aria-label="Twitter">
                <i class="fab fa-twitter ms-3"></i>
            </a>
            <a href="https://www.instagram.com" target="_blank" aria-label="Instagram">
                <i class="fab fa-instagram ms-3"></i>
            </a>
            <a href="https://www.youtube.com" target="_blank" aria-label="Youtube">
                <i class="fab fa-youtube ms-3"></i>
            </a>
        </p>
    </footer>

    <!-- Alert Close function -->
    <script>
        setTimeout(function () {
            let messages = document.getElementById('msg');
            let alert = new bootstrap.Alert(messages);
            alert.close();
        }, 3500);
    </script>
</body>

</html>

templates/contact_us.html
{% extends 'base.html' %}

{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-md-8 mt-3 offset-md-2">
                <h1>Contact</h1>
                    <p class="lead">
                        Reel in your thoughts, hook me with your suggestions,
                        or cast your incredible fishing tales my way! I'm all
                        about fishing and fun at "Swedish Angler's Diary"
                        and I can't wait to hear from you. Whether it's tips, stories,
                        or anything fishy, drop me a line, and I'll be hooked on your message.
                    </p>
                    <p class="lead">Tight lines and happy fishing!</p>
                <form method="post">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <button class="btn btn-primary" type="submit">Submit</button>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

templates/fishing_journal/create_entry.html
{% extends 'base.html' %}

{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-md-8 mt-3 offset-md-2">
                <h1>Create Fishing Journal Entry</h1> <!-- Create Fishing Journal Entry -->
                <form method="post">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <button class="btn btn-primary" type="submit">Save Entry</button>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

templates/fishing_journal/delete_entry.html
{% extends 'base.html' %}

{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-md-8 mt-3 offset-md-2">
                <h1>Delete Fishing Journal Entry</h1> <!-- Delete Fishing Journal Entry -->
                <p class="lead">Are you sure you want to delete "{{ entry.title }}"?</p>
                <form method="post" action="{% url 'fishing_journal:delete_entry' entry.id %}">
                    {% csrf_token %}
                    <button type="submit" class="btn btn-danger">Delete</button>
                  </form>
            </div>
        </div>
    </div>
{% endblock %}

templates/fishing_journal/entry_base.html
{% extends 'base.html' %}

{% block content %}
    <header class="header py-4">
        <div class="container text-center">
            <h1>My Personal Fishing Journal</h1>
            <p class="lead">Keep track of your fishing adventures and memories.</p>
        </div>
    </header>
    <div class="container-fluid text-center">
        <div class="row">
            <div class="col-12 mt-3 left">
                <a href="{% url 'fishing_journal:create_entry' %}" class="btn btn-primary">Create an Entry</a>
            </div>
        </div>
    </div>
    <!-- Entry Card Position -->
    <div class="container-fluid text-center">
        <div class="row">
            <div class="col-12 mt-3 left">
                <div class="row">
                    {% for entry in entries %}
                    <div class="col-md-6 col-lg-3">
                        <div class="mb-4 entry-card">
                            <div class="card-body">
                                <h2 class="card-title">{{ entry.title }}</h2>
                                <p class="card-text">Location: {{ entry.location }}</p>
                                <p class="card-text">Date: {{ entry.date }}</p>
                                <p class="card-text">Catch Details: {{ entry.catch_details }}</p>
                                <p class="card-text">Notes: {{ entry.notes }}</p>
                                <!-- Add Edit and Delete Buttons -->
                                <a href="{% url 'fishing_journal:update_entry' entry.id %}" class="btn btn-primary">Edit</a>
                                <a href="{% url 'fishing_journal:delete_entry' entry.id %}" class="btn btn-primary">Delete</a>
                            </div>
                        </div>
                    </div>
                    {% if forloop.counter|divisibleby:4 %}
                </div>
                <div class="row">
                    {% endif %}
                    {% endfor %}
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/fishing_journal/update_entry.html
{% extends 'base.html' %}

{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-md-8 mt-3 offset-md-2">
                <h1>Update Fishing Journal Entry</h1> <!-- Update Fishing Journal Entry -->
                <form method="post">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <button class="btn btn-primary" type="submit">Update Entry</button>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

templates/index.html
{% extends "base.html" %}

{% block content %}

<div class="container-fluid">
    <div class="row">

        <!-- Blog Entries Col -->
        <div class="col-12 mt-3 left">
            <div class="row">
                {% for post in post_list %}
                <div class="col-md-4">
                    <div class="card mb-4">
                        <div class="card-body">
                            <div class="image-container">
                                {% if "placeholder" in post.featured_image.url %}
                                <img class="card-img-top"
                                    src="https://placehold.co/400" alt="{{ post.title }}" style="width: 100%;">
                                {% else %}
                                <img class="card-img-top" src=" {{ post.featured_image.url }}" alt="{{ post.title }}" style="width: 100%;">
                                {% endif %}
                                <div class="image-flash">
                                    <p class="author">Author: {{ post.author }}</p>
                                </div>
                            </div>
                            <a href="{% url 'post_detail' post.slug %}" class="post-link">
                                <h2 class="card-title">{{ post.title }}</h2>
                                <p class="card-text">{{ post.excerpt }}</p>
                            </a>
                            <hr />
                            <p class="card-text" id="postdetails">{{ post.created_on}} <i class="far fa-heart"></i>
                                {{ post.number_of_likes }}</p>
                        </div>
                    </div>
                </div>
                {% if forloop.counter|divisibleby:3 %}
            </div>
            <div class="row">
                {% endif %}
                {% endfor %}
            </div>
        </div>
    </div>
</div>
{%endblock%}

templates/post_detail.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block content %}

<div class="masthead">
    <div class="container">
        <div class="row g-0">
            <div class="col-md-6 masthead-text">
                <!-- Post title goes in these h1 tags -->
                <h1 class="post-title">{{ post.title }}</h1>
                <!-- Post author goes before the | the post's created date goes after -->
                <p class="post-subtitle">{{ post.author }} | {{ post.created_on }}</p>
            </div>
            <div class="d-none d-md-block col-md-6 masthead-image">
                <!-- The featured image URL goes in the src attribute -->
                {% if "placeholder" in post.featured_image.url %}
                    <img src="https://placehold.co/400" width="100%">
                {% else %}
                    <img src="{{ post.featured_image.url }}" width="100%">
                {% endif %}
            </div>
        </div>
    </div>
</div>

<div class="container">
    <div class="row">
        <div class="col card mb-4 mt-3 left top">
            <div class="card-body">
                <div class="card-body">
                    {% if post.excerpt %}
                        <p class="card-text">{{ post.excerpt | safe }}</p>
                    {% endif %}
                    <p class="card-text">{{ post.content | safe }}</p>
                </div>
                <div class="row">
                    <div class="col-1">
                        <strong>
                            {% if user.is_authenticated %}
                                <form class="d-inline" action="{% url 'post_like' post.slug %}" method="POST">
                                    {% csrf_token %}
                                    {% if liked %}
                                        <button type="submit" name="blogpost_id" value="{{ post.slug }}" class="btn-like"><i class="fas fa-heart"></i></button>
                                    {% else %}
                                        <button type="submit" name="blogpost_id" value="{{ post.slug }}" class="btn-like"><i class="far fa-heart"></i></button>
                                    {% endif %}
                                </form>
                            {% else %}
                                <span class="text-secondary"><i class="far fa-heart"></i></span>
                            {% endif %}
                            <span class="text-secondary">{{ post.number_of_likes }}</span>
                        </strong>
                    </div>
                    <div class="col-1">
                        {% with comments.count as total_comments %}
                            <strong class="text-secondary"><i class="far fa-comments"></i>
                                {{ total_comments }}
                            </strong>
                        {% endwith %}
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col">
            <hr>
        </div>
    </div>
    <!-- Comment Loop -->
    <div class="row">
        <div class="col-md-8 card mb-4 mt-3">
            <h3>Comments:</h3>
            <div class="card-body">
                {% for comment in comments %}
                    <div class="comments" style="padding: 10px;">
                        <p class="font-weight-bold">
                            {{ comment.name }}
                            <span class="text-muted font-weight-normal">
                                {{ comment.created_on }}
                            </span> wrote:
                        </p>
                        {{ comment.body | linebreaks }}
                    </div>
                {% endfor %}
            </div>
        </div>
        <!-- Awaiting Approval Msg -->
        <div class="col-md-4 card mb-4 mt-3">
            <div class="card-body">
                {% if commented %}
                    <div class="alert alert-success" role="alert">
                        Your comment is awaiting approval
                    </div>
                {% else %}
                    {% if user.is_authenticated %}
                        <h3>Leave a comment:</h3>
                        <p>Posting as: {{ user.username }}</p>
                        <form method="post" style="margin-top: 1.3em;">
                            {{ comment_form | crispy }}
                            {% csrf_token %}
                            <button type="submit" class="btn btn-primary">Submit</button>
                        </form>
                    {% endif %}
                {% endif %}
            </div>
        </div>
    </div>
</div>

{% endblock content %}